### ISSUE TITLE
error: ‘cvCopyImage’ was not declared in this scope     cvCopyImage(byteImg, bigImg);

### ISSUE THREAD

**Issue by hqf2591102423** [pengxinyi-up/mobile-grab-Robot#1]
can it compile in Ubuntu18.04，i  do it .but it comes to that
![2022-01-15 15-10-28 的屏幕截图](https://user-images.githubusercontent.com/88996506/149613068-0a5771ee-3813-446c-8601-5513a3f6254d.png)
